#!/bin/bash

source ~/venv/bin/activate

Z=~/Zones
export PYTHONPATH=$PYTHONPATH:$Z

authbind --deep twistd dns \
    --pyzone $Z/twistedmatrix.com \
    --pyzone $Z/divunal.com \
    --pyzone $Z/intarweb.us \
    --pyzone $Z/ynchrono.us \
    --pyzone $Z/divmod.com \
    --pyzone $Z/divmod.org
