#!/usr/bin/python

import os

service = %(service)r
args = %(args)r
env = %(env)r
withAuthbind = %(withAuthbind)r

pidfile = os.path.join(os.path.expanduser('~/var/run/'),
                       service + '.pid')
logfile = os.path.join(os.path.expanduser('~/var/log/'),
                       service + '.log')

command = [
    'twistd',
    '--pidfile', pidfile,
    '--logfile', logfile]

if withAuthbind:
    command = [ 'authbind', '--deep' ] + command

os.chdir(os.path.expanduser('~'))
os.execve(command[0], command + args, env)
