#!/usr/bin/python

import sys, os

from twisted.python import log

import config, commit

if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit("Usage: %s <repository path> <revision number>" % (sys.argv[0],))
    log.startLogging(
        file(os.path.expanduser(
            os.path.join(config.LOG_ROOT, '.commit.log')), 'a'))
    commit.main(sys.argv[1], int(sys.argv[2]))
