#!/usr/bin/python

import os, sys

from twisted.python.log import startLogging

import config, message

if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit("Usage: %s <channel> <message>" % (sys.argv[0],))
    startLogging(file(
        os.path.expanduser(
            os.path.join(config.LOG_ROOT, '.message.log')), 'a'))
    message.main(*sys.argv[1:])
