#!/usr/bin/python

import sys, os

from twisted.python import log

import config, ticket

if __name__ == '__main__':
    if len(sys.argv) != 7:
        raise SystemExit("Usage: %s <tracker url> <ticket id> <author> <kind> <component> <subject>" % (sys.argv[0],))
    log.startLogging(
        file(os.path.expanduser(
            os.path.join(config.LOG_ROOT, '.ticket.log')), 'a'))
    ticket.main(*sys.argv[1:])
